54.1 Downloading django_cors_headers-3.8.0-py3-none-any.whl (12 kB)
154.5 Downloading djangorestframework-3.12.4-py3-none-any.whl (957 kB)
154.8    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 957.7/957.7 kB 3.7 MB/s eta 0:00:00
155.3 Downloading pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
155.4    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 4.1 MB/s eta 0:00:00
155.8 Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
156.1    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.8/510.8 kB 4.6 MB/s eta 0:00:00
156.7 Downloading sqlparse-0.4.2-py3-none-any.whl (42 kB)
156.8    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 29.5 MB/s eta 0:00:00
157.3 Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
158.7 Building wheels for collected packages: Pillow
158.8   Building wheel for Pillow (setup.py): started
162.6   Building wheel for Pillow (setup.py): finished with status 'error'
162.8   error: subprocess-exited-with-error
162.8   
162.8   × python setup.py bdist_wheel did not run successfully.
162.8   │ exit code: 1
162.8   ╰─> [196 lines of output]
162.8       /usr/local/lib/python3.11/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
162.8       !!
162.8       
162.8               ********************************************************************************
162.8               Please consider removing the following classifiers in favor of a SPDX license expression:
162.8       
162.8               License :: OSI Approved :: Historical Permission Notice and Disclaimer (HPND)
162.8       
162.8               See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
162.8               ********************************************************************************
162.8       
162.8       !!
162.8         self._finalize_license_expression()
162.8       running bdist_wheel
162.8       running build
162.8       running build_py
162.8       creating build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/TarIO.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/_version.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/features.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/_util.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/__init__.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/_binary.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/__main__.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/FontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/Image.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
162.8       running egg_info
162.8       writing src/Pillow.egg-info/PKG-INFO
162.8       writing dependency_links to src/Pillow.egg-info/dependency_links.txt
162.8       writing top-level names to src/Pillow.egg-info/top_level.txt
162.8       reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
162.8       reading manifest template 'MANIFEST.in'
162.8       warning: no files found matching '*.c'
162.8       warning: no files found matching '*.h'
162.8       warning: no files found matching '*.sh'
162.8       warning: no previously-included files found matching '.appveyor.yml'
162.8       warning: no previously-included files found matching '.clang-format'
162.8       warning: no previously-included files found matching '.coveragerc'
162.8       warning: no previously-included files found matching '.editorconfig'
162.8       warning: no previously-included files found matching '.readthedocs.yml'
162.8       warning: no previously-included files found matching 'codecov.yml'
162.8       warning: no previously-included files matching '.git*' found anywhere in distribution
162.8       warning: no previously-included files matching '*.pyc' found anywhere in distribution
162.8       warning: no previously-included files matching '*.so' found anywhere in distribution
162.8       no previously-included directories found matching '.ci'
162.8       adding license file 'LICENSE'
162.8       writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
162.8       running build_ext
162.8       
162.8       
162.8       The headers or library files could not be found for zlib,
162.8       a required dependency when compiling Pillow from source.
162.8       
162.8       Please see the install instructions at:
162.8          https://pillow.readthedocs.io/en/latest/installation.html
162.8       
162.8       Traceback (most recent call last):
162.8         File "/tmp/pip-install-_hunpxut/pillow_632e20321b0d467bb98fc93e32451773/setup.py", line 976, in <module>
162.8           setup(
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
162.8           return distutils.core.setup(**attrs)
162.8                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 186, in setup
162.8           return run_commands(dist)
162.8                  ^^^^^^^^^^^^^^^^^^
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
162.8           dist.run_commands()
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
162.8           self.run_command(cmd)
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1104, in run_command
162.8           super().run_command(command)
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
162.8           cmd_obj.run()
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/command/bdist_wheel.py", line 370, in run
162.8           self.run_command("build")
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 357, in run_command
162.8           self.distribution.run_command(command)
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1104, in run_command
162.8           super().run_command(command)
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
162.8           cmd_obj.run()
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
162.8           self.run_command(cmd_name)
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 357, in run_command
162.8           self.distribution.run_command(command)
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1104, in run_command
162.8           super().run_command(command)
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
162.8           cmd_obj.run()
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 99, in run
162.8           _build_ext.run(self)
162.8         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 368, in run
162.8           self.build_extensions()
162.8         File "/tmp/pip-install-_hunpxut/pillow_632e20321b0d467bb98fc93e32451773/setup.py", line 788, in build_extensions
162.8           raise RequiredDependencyException(f)
162.8       RequiredDependencyException: zlib
162.8       
162.8       During handling of the above exception, another exception occurred:
162.8       
162.8       Traceback (most recent call last):
162.8         File "<string>", line 2, in <module>
162.8         File "<pip-setuptools-caller>", line 34, in <module>
162.8         File "/tmp/pip-install-_hunpxut/pillow_632e20321b0d467bb98fc93e32451773/setup.py", line 1035, in <module>
162.8           raise RequiredDependencyException(msg)
162.8       RequiredDependencyException:
162.8       
162.8       The headers or library files could not be found for zlib,
162.8       a required dependency when compiling Pillow from source.
162.8       
162.8       Please see the install instructions at:
162.8          https://pillow.readthedocs.io/en/latest/installation.html
162.8       
162.8       
162.8       [end of output]
162.8   
162.8   note: This error originates from a subprocess, and is likely not a problem with pip.
162.8   Running setup.py clean for Pillow
162.8   ERROR: Failed building wheel for Pillow
164.1 Failed to build Pillow
164.1 ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects
167.9 
167.9 [notice] A new release of pip is available: 24.0 -> 25.3
167.9 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:8
--------------------
   6 |     # Copy requirements and install dependencies
   7 |     COPY requirements.txt .
   8 | >>> RUN pip3 install --default-timeout=100 --no-cache-dir -r requirements.txt
   9 |     
  10 |     # Copy the rest of the application
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c pip3 install --default-timeout=100 --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
